<?php

use Illuminate\Database\Seeder;

class DescriptionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 44" (112cm)<br>Tamaño compacto<br>Garantía por un año</br>Software RIP "Wasatch" incluido</br>Secado extremadamente rápido</br>Tanques de capacidad de 1.5 l rellenables </br>Velocidades de impresión de hasta 63 m²/h</br>Compatible con los principales papeles de transferencia por sublimación de tinta</br>Tecnología desarrollada para sublimación de nivel industrial','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 64" (162.5cm)<br>Tamaño compacto<br>Garantía por un año<br>Software RIP "Wasatch" incluido<br>Secado extremadamente rápido<br>Tanques de capacidad de 1.5 l rellenables <br>Mayor velocidad gracias a su nueva tecnología<br>Sistema integrado para enrollar de manera automatica la impresión<br>Compatible con los principales papeles de transferencia por sublimación de tinta<br>Gracias al rodillo de secado permite un secado rápido para una producción de rollo a rollo','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 16"x 20" (40.6 x 50.8)<br>Gracias al sistema recirculatorio de tinta permite más duración con menos mantenimiento<br>Incluye un software muy completo y fácil de usar<br>Alta densidad en tinta blanca para un blanco más natural <br>Para impresión directa en playeras de 100% algodón hasta 50/50<br>Sistema de scanéo automatico para evitar golpes en el cabezal <br>Diferentes tamaños de placas para impresión en distintas medidas 4" X 4" para mangas, 10" x 12" para chicas, 14" x 16" para medianas, 16" x 20" para grandes','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 64" (162.5 cm)<br>Garantía de un año<br>Cabezal garantizado<br>Software ONYX incluido<br>Sin necesidad de filtros de aire<br>Secado extremadamente rápido<br>Velocidades de impresión de hasta 57m2/h<br>Resolución que se adecua a tus necesidades <br>Cuida tu salud y la de tus empleados con la tinta eco-solvente sin olor y sin los elementos cancerígenos de la tinta convencional <br>Un impacto menor al ambiente a comparación de otras máquinas','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 64" (162.5 cm)<br>Doble cabezal <br>Garantía de un año <br>Cabezal garantizado<br>Software ONYX incluido<br>Sin necesidades de filtros de aire<br>Velocidades de impresión de hasta 91.04 m2/h<br>Resolución que se adecua a tus necesidades <br>Cuida tu salud y la de tus empleados con la tinta eco-solvente sin olor y sin los elementos cancerígenos de la tinta convencional <br>Un impacto menor al ambiente a comparación de otras máquinas','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 64" (162.5 cm)<br>Doble cabezal <br>Garantía de un año <br>Cabezal garantizado<br>Software ONYX incluido<br>Sin necesidades de filtros de aire<br>Secado extremadamente rápido<br>Resolución que se adecua a tus necesidades <br>Cuida tu salud y la de tus empleados con la tinta eco-solvente sin olor y sin los elementos cancerígenos de la tinta convencional <br>Un impacto menor al ambiente a comparación de otras máquinas','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 24" (61cm)<br>Garantía de un año<br>Velocidad de hasta 237.74m2/h<br>Tintas diseñadas para resistir el uso al aire libre<br>Diseñada para recibir papeles hasta de 1,5 mm de espesor<br>Sistema de alta capacidad en tintas para abaratar costos<br>Canasta para capturar impresiones y apilarlas cuidadosamente','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 36" (91cm)<br>Garantía de un año<br>CON OPCIÓN DE CONVERTIRSE EN MULTIFUNCIONAL al agregar el escáner <br>Velocidad de hasta 237.74m2/h<br>Tintas diseñadas para resistir el uso al aire libre<br>Diseñada para recibir papeles hasta de 1,5 mm de espesor<br>Sistema de alta capacidad en tintas para abaratar costos<br>Canasta para capturar impresiones y apilarlas cuidadosamente','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 44" (111cm)<br>Garantía de un año<br>CON OPCIÓN DE CONVERTIRSE EN MULTIFUNCIONAL al agregar el escáner <br>Velocidad de hasta 237.74m2/h<br>Tintas diseñadas para resistir el uso al aire libre<br>Diseñada para recibir papeles hasta de 1,5 mm de espesor<br>Sistema de alta capacidad en tintas para abaratar costos<br>Canasta para capturar impresiones y apilarlas cuidadosamente','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 36" (91cm)<br>Garantía de un año<br>Velocidad de hasta 237.74m2/h<br>Ahorra tiempo con el cambio automático de rollo<br>-Utiliza el tamaño adecuado de papel para cada trabajo<br>-Cambia de medio para hacer trabajos de alta calidad<br>-Duplica la producción del mismo medio sin la necesidad de supervisar<br>Tintas diseñadas para resistir el uso al aire libre<br>Diseñada para recibir papeles hasta de 1,5 mm de espesor<br>Sistema de alta capacidad en tintas para abaratar costos<br>Canasta para capturar impresiones y apilarlas cuidadosamente','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 44" (111cm)<br>Garantía de un año<br>Velocidad de hasta 237.74m2/h<br>Ahorra tiempo con el cambio automático de rollo<br>-Utiliza el tamaño adecuado de papel para cada trabajo<br>-Cambia de medio para hacer trabajos de alta calidad<br>-Duplica la producción del mismo medio sin la necesidad de supervisar<br>Tintas diseñadas para resistir el uso al aire libre<br>Diseñada para recibir papeles hasta de 1,5 mm de espesor<br>Sistema de alta capacidad en tintas para abaratar costos<br>Canasta para capturar impresiones y apilarlas cuidadosamente','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho:</strong> 36"(91 cm) o 44" (111cm)<br>La copiadora y escáner más rápido de su clase.<br>Copia a colorhasta en 40 segundos<br>Escaneo de 6 pulgadas por segundo<br>Comparte lo que escaneaste por la red o correo electrónico<br>Copias, ampliaciones y escaneos fáciles y rápidos','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 8.5" (21.6 cm)<br>Resolución de impresión de 5760dpi<br>Impresión sobre CDs y DVDs imprimibles<br>Imprime tus documentos y fotos a un costo mucho más bajo<br>Garantiza una calidad de impresión incomparable, la cual realiza los más<br>mínimos detalles gracias a sus 6 colores y tinta de secado instantáneo','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 13" (33cm)<br>Software para edición de fotos GRATIS<br>Súper alta productividad con altísimo rendimiento<br>Bajo costo de operación con el nuevo sistema de tanques de tinta de Epson<br>Alta calidad de impresión y confiabilidad con las tintas originales Epson<br>Convenientemente fácil de usar, rellenar y con la garantía original Epson','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 17" (43 cm)<br>Tecnología que reduce la diferencia de brillos.<br>Color estable inmediatamente al imprimir sin cambio de color a corto plazo<br>Imprime en cualquier tipo de papel de arte<br>Gracias a su gama de negros produce fotos profesionales en blanco y negro o color','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 17" (43cm)<br>Alta resolución para increíble textos sombreados y dibujos lineales<br>Mejoramiento en balance de blancos <br>Pantalla LCD que permite revisar el estado de la impresora<br>Gracias a su tecnología automatiza prácticamente cualquier proceso de gestión de color<br>Incluye un software muy fácil de usar','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 24" (60 cm)<br>Thin Film Piezo(TFP) diseño de la cabeza de impresión capaz de manejar ocho canales de tintas independientes<br>Tecnología para reducir drásticamente la obstrucción de la boquilla<br>Manejo de soportes profesionales<br>Compatible con prácticamente cualquier tipo de medio, en rollos o cortadas en hojas','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 24"(60cm)<br>El resultado es un color constante para cumplimiento del colorido<br>Calibración de color durante el proceso de fabricación<br>Excepcional precisión a al sombra en escala de grises para una gama tonal más suave<br>Tecnología de cartuchos de tinta a presión para asegurar el suministro de tinta fiable a todas las velocidades de impresión<br>Espectrofotómetro de 24 desarrollado conjuntamente con X-Rite','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 44" (111 cm)<br>Thin Film Piezo(TFP) diseño de la cabeza de impresión capaz de manejar ocho canales de tintas independientes<br>Tecnología para reducir drásticamente la obstrucción de la boquilla<br>Manejo de soportes profesionales<br>Compatible con prácticamente cualquier tipo de medio, en rollos o cortadas en hojas','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> 44"(111cm)<br>El resultado es un color constante para cumplimiento del colorido<br>Calibración de color durante el proceso de fabricación<br>Excepcional precisión a al sombra en escala de grises para una gama tonal más suave<br>Tecnología de cartuchos de tinta a presión para asegurar el suministro de tinta fiable a todas las velocidades de impresión<br>Espectrofotómetro de 24 desarrollado conjuntamente con X-Rite','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> Tabloide Super B(330 x 483 mm)<br>Con la capacidad única de aplicar tóner blanco o tóner transparente con acabado brillante, además de los colores CMYK<br>Ideal para producción en multiples sustratos hasta de 360gr/m, desde tarjetas de 3" x 5" hasta banderines o pancartas de 1.32 m<br>Consumibles de alta capacidad hasta 38,000 páginas<br>Con kit de color para conseguir efectos espectaculares en sustratos opacos, traslúsidos o transparentes sin ningun problema con sólo cambiar en minutos la quinta estación de color de blanco o transparente','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Ancho máximo:</strong> Tabloide Super B(330 x 483 mm)<br>Resultados asombrosos a una velocidad impresionante <br>Con la más alta tecnología en LED para impresión<br>Ideal para producción en multiples sustratos hasta de 360gr/m, desde tarjetas de 3" x 5" hasta banderines o pancartas de 1.32 m<br>Consumibles de alta capacidad hasta 38,000 páginas<br>Incluye dúplex automático y red','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Tamaño:</strong>Ancho máximo: 11" x 14" (29x 38 cm)<br><strong>Temperatura Máxima: </strong>225°C<br><strong>Voltaje: </strong>110V<br>Equipo multifuncional<br>Control digital de temperatura<br>Alarma de tiempo automática<br>Rango de tiempo de 0 -999 seg<br>Con los accesorios : Plancha plana 29 x 38cm, Resistencia plato 8"<br>Resistencia plato 10"<br>Resistencia taza 10 oz<br>Resistencia taza 11 oz<br>Resistencia conica 12 oz<br>Resistencia conica 17 oz<br>Resistencia para Gorras','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Tamaño:</strong>Ancho máximo: 15" x 19" (40 x 50 cm)<br><strong>Temperatura Máxima: </strong>225°C<br><strong>Voltaje: </strong>110V<br>Presión 70-75<br>Cubierta protectora anti-quemaduras<br>Pistón de gas fácil apertura<br>Placa deslizable<br>Angulo de apertura de 25°<br>Rango de tiempo 0-999<br>Alarma de tiempo automática','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Tamaño:</strong>Ancho máximo: 100 x 120 cm<br><strong>Temperatura Máxima: </strong>399°C<br><strong>Voltaje: </strong>3 fases 220V<br>Diseñada con dos mesas de trabajo en un solo lado de la maquina.<br>Cuando la impresión finaliza la mesa automaticamente rueda hacia afuera de la maquina mientras la otra rueda hacia adentrO para ser planchada.<br>Las mesas de trabajo estan fabricadas con placas de aluminio solido lo que las hacen altamente estables.<br>El diseño de la plancha termica esta perfectamente uniforme, esto garantiza una impresión de alta calidad.<br>Potencia de 9 kw a 12 kw<br>Rango de tiempo ajustable<br>Presión neumática 8kg/cm2','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Capacidad: </strong>70 ml','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Capacidad: </strong>80 ml','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Capacidad: </strong>950 ml','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Capacidad: </strong>350 ml','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Capacidad: </strong>950 ml','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Capacidad: </strong>600 ml','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Capacidad: </strong>13 ml','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Capacidad: </strong>200 ml','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Capacidad: </strong>220 ml','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Capacidad: </strong>220 ml','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Capacidad: </strong>7 ml','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Capacidad: </strong>220 ml','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Capacidad: </strong>700 ml','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Anchos:</strong> 17"(43.18cm), 18"(45.72cm), 24"(60.96cm)<br><strong>Largo:</strong> 45.72 M<br>Ideal para la creación de aplicaciones en colores lisos, EasyWeed™ se aplica a una temperatura baja, se pela en frio o caliente, es extremadamente delagado y se pueden poner varias capas del mismo.<br>Gracias a que esta compuesto de Puliuretano es seguro para niños y adultos<br>Indicaciones de planchado<br>- Tiempo: 10-15 seg<br>- Temperatura:305°F/150°C    <br>- Presión: Media  <br>- Pelado: Frio o Caliente','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Anchos:</strong> 15"(38.1cm)<br><strong>Largo:</strong> 23 M<br>Ideal para la creación de aplicaciones en NYLON, EasyWeed Extra se adhiere al NYLON, se puede pelar en frio y caliente, deja un acabado semi-gloss y se puede poner en varias capas.<br>- Tiempo: 10-15 seg<br>- Temperatura:310°F/160°C    <br>- Presión: Media  <br>- Pelado: Frio o Caliente','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Anchos:</strong> 15"(38.1cm)<br><strong>Largo:</strong> 23 M<br>Super elasticidad y el mas delgado de la industria, tiene un acabado ultra-matte y suave al tacto, disponible en 12 colores incluyendo el oro y el plata. <br>Indicaciones de planchado<br>- Tiempo: 10-15 seg<br>- Temperatura:310°F/160°C    <br>- Presión: Media  <br>- Pelado: Frio','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Anchos:</strong> 20"(50.2cm)<br><strong>Largo:</strong> 23 M<br>Nuestros colores te preveran del maximo uso de brillos, nuestro producto esta certificado y esto genera que lo puedas poner en ropa para niños y si se ingiere no pasa nada. Nusetro vinil tien ebrillantina encapsulada por lo cual no se desprenderan los brillos. <br>Indicaciones de planchado<br>- Tiempo: 10-15 seg<br>- Temperatura:310°F/160°C    <br>- Presión: firme<br>- Pelado: Frio o Caliente','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Anchos:</strong> 20"(50.2cm)<br><strong>Largo:</strong> 25 M<br>Es el vinil perfecto para deportes como poner nombres a jerseys logos, numeros, etc. Prepara todo un equipo deportivo al mas bajo precio. <br>Indicaciones de planchado<br>- Tiempo: 10-15 seg<br>- Temperatura:310°F/160°C    <br>- Presión: Media  <br>- Pelado: Frio','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Anchos:</strong> 17"(43.18cm), 18"(45.72cm), 24"(60.96cm)<br><strong>Largo:</strong> 25 M<br>Es un vinil delgado y elastico que se puede cortar, puedes generar un patron de color estriable desde la comodidad de tu impresora de solvente o ecosolvente y la ventaja se pela inmediatamente despues de aplicarse. <br>Indicaciones de planchado<br>- Tiempo: 10-15 seg<br>- Temperatura:310°F/160°C    <br>- Presión: Media  <br>- Pelado: Frio o Caliente','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Anchos:</strong> 18"(45.72cm)<br><strong>Largo:</strong> 46 M<br>Una cinta de transferencia que permite colocar la imagen con presión en la prenda pero también libera fácilmente después de la aplicacion de calor.','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Anchos:</strong> 15"(38.1cm)<br><strong>Largo:</strong> 45.72 M<br>Dale a tus logos un relieve, texturizado o un tacto especial. Este vinil es excellente para estilos retros, es muy opaco y profundo lo cual produce una gran sensación.<br>Indicaciones de planchado<br>- Tiempo: 15-20 seg<br>- Temperatura:310°F/160°C    <br>- Presión: Media  <br>- Pelado: Frio','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Anchos:</strong> 20" (50.2cm)<br><strong>Largo:</strong> 22.86 M<br>El vinil holographico esta disponible en muchos efectos especiales que llevaran tu ropa a otro nivel, y se puede cortar como si fueren pedreria lo cual generara un diseño de pedreria sin piedras. <br>Indicaciones de planchado<br>- Tiempo: 10-15 seg<br>- Temperatura:310°F/160°C    <br>- Presión: Fuerte  <br>- Pelado: Frio','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Volúmen: </strong>100 hojas<br><strong>Medidas: </strong>4x6/5x7/6x8/11x14/17x22/8.5x11"','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Volúmen: </strong>100 hojas<br><strong>Medidas: </strong>4x6" /5x7" /6x8" /11x14"','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Volúmen: </strong>50 hojas<br><strong>Medidas: </strong>17x22"','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Volúmen: </strong>25 hojas<br><strong>Medidas: </strong>8.5x11"','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Volúmen: </strong>50 hojas<br><strong>Medidas: </strong>8.5x11"','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Volúmen: </strong>50 hojas<br><strong>Medidas: </strong>8.5x11"','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Volúmen: </strong>450 hojas<br><strong>Medidas: </strong>8.5x11"','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Volúmen: </strong>50 hojas<br><strong>Medidas: </strong>8.5x11"','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Volúmen: </strong>50 hojas<br><strong>Medidas: </strong>8.5x11" / 11.7x16.5"','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Volúmen: </strong>25 hojas<br><strong>Medidas: </strong>17x22"','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Volúmen: </strong>25 hojas<br><strong>Medidas: </strong>17x22"','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Volúmen: </strong>100 hojas<br><strong>Medidas: </strong>4x6"','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Volúmen: </strong>150 hojas<br><strong>Medidas: </strong>4x6"','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 105gr<br><strong>Largo:</strong> 91 M<br><strong>Ancho:</strong>24"(60.96cm) / 44"(112 cm) / 64"(162.54cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 100gr<br><strong>Largo:</strong> 106 M<br><strong>Ancho:</strong>44"(112 cm) / 64"(162.54cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 75 gr<br><strong>Largo:</strong> 152 M<br><strong>Ancho:</strong>44"(112 cm) / 64"(162.54cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 100 gr<br><strong>Largo:</strong> 100 M<br><strong>Ancho:</strong>24"(60.96cm) / 36"(91.44cm) /44"(112 cm) / 54"(137.16cm) / 64"(162.54cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 100 gr<br><strong>Largo:</strong> 100 M<br><strong>Ancho:</strong>36"(91.44cm) / 44"(112 cm) / 64"(162.54cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 250 gr<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>60" (152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 414 gr<br><strong>Largo:</strong> 22 M<br><strong>Ancho:</strong>60" (152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 248 gr<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>60" (152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 200 gr<br><strong>Largo:</strong> 50 M<br><strong>Ancho:</strong>50"(127cm) / 60" (152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 248 gr<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>60" (152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 160 gr<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>60" (152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 100 gr<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>60" (152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> N/A<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>60" (152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> N/A<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>60" (152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 450 hilos / 300 hilos / 150 hilos<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>60" (152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 100 gr<br><strong>Largo:</strong> 50 M<br><strong>Ancho:</strong>60" (152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 100 gr<br><strong>Largo:</strong> 50 M<br><strong>Ancho:</strong>60" (152.4cm) / 54" (137.16cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 100 gr<br><strong>Largo:</strong> 50 M<br><strong>Ancho:</strong>60" (152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> N/A<br><strong>Largo:</strong> 50 M<br><strong>Ancho:</strong>62" (157.48cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> N/A<br><strong>Largo:</strong> 50 M<br><strong>Ancho:</strong>62" (157.48cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 13oz<br><strong>Largo:</strong> 50 M<br><strong>Ancho:</strong>60" (152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> N/A<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>60" (152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 250 gr<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>16"(40.64cm) / 24"(60.96cm) / 36"(91.44cm) / 44"(112 cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 260 gr<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>16"(40.64cm) / 24"(60.96cm) / 36"(91.44cm) / 44"(112 cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> N/A<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>17"(43.18cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 180 gr<br><strong>Largo:</strong> 25 M<br><strong>Ancho:</strong>24"(60.96cm)/ 36"(91.44cm) / 44"(112 cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 260 gr<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>17"(43.18cm)/ 24"(60.96cm) / 36"(91.44cm) / 42"(106.68cm)/ 44"(112 cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 260 gr<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>17"(43.18cm)/ 24"(60.96cm) / 36"(91.44cm) / 42"(106.68cm)/ 44"(112 cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
		DB::table('descriptions')->insert(['body' => '<strong>Gramaje:</strong> 260 gr<br><strong>Largo:</strong> 30 M<br><strong>Ancho:</strong>10"(25.4 cm)/ 16"(40.64cm) / 20"(50.8cm) / 24"(60.96cm) / 36"(91.44cm) / 44"(112 cm) / 60"( 152.4cm)','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString()]);
    }
}
