<?php

use Illuminate\Database\Seeder;

class TechniqueTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('techniques')->insert(['title' => 'Sublimacion','about' => 'Turpis turpis odio enim. Urna eu rhoncus nisi? Aliquet placerat magnis porta nisi? Eros porttitor a! Dignissim sit, non placerat, et! Magna, sit habitasse, mattis integer in, egestas purus augue quis tincidunt? Est, vut, natoque! Porta velit augue dis auctor aliquet augue augue scelerisque! Sed, penatibus rhoncus nascetur? Vel placerat pulvinar tincidunt urna ut, phasellus lorem non mus porta et nunc, ultrices eu nascetur, sagittis, mattis dictumst cras dignissim, integer. Aliquam magnis. Nunc amet ultrices rhoncus et tortor mus auctor, integer tortor pellentesque, ultrices placerat ac quis arcu elit, proin.','detail' => 'Massa, phasellus massa, ac pellentesque, auctor rhoncus aliquet dis, tempor dis sociis auctor! Ultricies urna dolor vut. Placerat pellentesque ut enim lorem urna egestas, integer adipiscing etiam eu, et eros pulvinar lundium tincidunt eu pid, pellentesque adipiscing augue tincidunt rhoncus lacus? Dictumst egestas, eros. Nascetur mid mus adipiscing tincidunt magna rhoncus a duis odio! Ridiculus odio facilisis, tempor, nunc, vel sit. Nisi augue pulvinar pulvinar eu nisi sagittis scelerisque! In amet! Phasellus pulvinar proin mauris dis vut cras integer ultrices! In ultrices, sed scelerisque pellentesque aliquet placerat turpis dignissim.','image' => 'na.png','user_id' => '1','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),'deleted_at' => null]);
        DB::table('techniques')->insert(['title' => 'Sublimacion','about' => 'Turpis turpis odio enim. Urna eu rhoncus nisi? Aliquet placerat magnis porta nisi? Eros porttitor a! Dignissim sit, non placerat, et! Magna, sit habitasse, mattis integer in, egestas purus augue quis tincidunt? Est, vut, natoque! Porta velit augue dis auctor aliquet augue augue scelerisque! Sed, penatibus rhoncus nascetur? Vel placerat pulvinar tincidunt urna ut, phasellus lorem non mus porta et nunc, ultrices eu nascetur, sagittis, mattis dictumst cras dignissim, integer. Aliquam magnis. Nunc amet ultrices rhoncus et tortor mus auctor, integer tortor pellentesque, ultrices placerat ac quis arcu elit, proin.','detail' => 'Massa, phasellus massa, ac pellentesque, auctor rhoncus aliquet dis, tempor dis sociis auctor! Ultricies urna dolor vut. Placerat pellentesque ut enim lorem urna egestas, integer adipiscing etiam eu, et eros pulvinar lundium tincidunt eu pid, pellentesque adipiscing augue tincidunt rhoncus lacus? Dictumst egestas, eros. Nascetur mid mus adipiscing tincidunt magna rhoncus a duis odio! Ridiculus odio facilisis, tempor, nunc, vel sit. Nisi augue pulvinar pulvinar eu nisi sagittis scelerisque! In amet! Phasellus pulvinar proin mauris dis vut cras integer ultrices! In ultrices, sed scelerisque pellentesque aliquet placerat turpis dignissim.','image' => 'na.png','user_id' => '1','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),'deleted_at' => null]);
        DB::table('techniques')->insert(['title' => 'Sublimacion','about' => 'Turpis turpis odio enim. Urna eu rhoncus nisi? Aliquet placerat magnis porta nisi? Eros porttitor a! Dignissim sit, non placerat, et! Magna, sit habitasse, mattis integer in, egestas purus augue quis tincidunt? Est, vut, natoque! Porta velit augue dis auctor aliquet augue augue scelerisque! Sed, penatibus rhoncus nascetur? Vel placerat pulvinar tincidunt urna ut, phasellus lorem non mus porta et nunc, ultrices eu nascetur, sagittis, mattis dictumst cras dignissim, integer. Aliquam magnis. Nunc amet ultrices rhoncus et tortor mus auctor, integer tortor pellentesque, ultrices placerat ac quis arcu elit, proin.','detail' => 'Massa, phasellus massa, ac pellentesque, auctor rhoncus aliquet dis, tempor dis sociis auctor! Ultricies urna dolor vut. Placerat pellentesque ut enim lorem urna egestas, integer adipiscing etiam eu, et eros pulvinar lundium tincidunt eu pid, pellentesque adipiscing augue tincidunt rhoncus lacus? Dictumst egestas, eros. Nascetur mid mus adipiscing tincidunt magna rhoncus a duis odio! Ridiculus odio facilisis, tempor, nunc, vel sit. Nisi augue pulvinar pulvinar eu nisi sagittis scelerisque! In amet! Phasellus pulvinar proin mauris dis vut cras integer ultrices! In ultrices, sed scelerisque pellentesque aliquet placerat turpis dignissim.','image' => 'na.png','user_id' => '1','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),'deleted_at' => null]);
        DB::table('techniques')->insert(['title' => 'Sublimacion','about' => 'Turpis turpis odio enim. Urna eu rhoncus nisi? Aliquet placerat magnis porta nisi? Eros porttitor a! Dignissim sit, non placerat, et! Magna, sit habitasse, mattis integer in, egestas purus augue quis tincidunt? Est, vut, natoque! Porta velit augue dis auctor aliquet augue augue scelerisque! Sed, penatibus rhoncus nascetur? Vel placerat pulvinar tincidunt urna ut, phasellus lorem non mus porta et nunc, ultrices eu nascetur, sagittis, mattis dictumst cras dignissim, integer. Aliquam magnis. Nunc amet ultrices rhoncus et tortor mus auctor, integer tortor pellentesque, ultrices placerat ac quis arcu elit, proin.','detail' => 'Massa, phasellus massa, ac pellentesque, auctor rhoncus aliquet dis, tempor dis sociis auctor! Ultricies urna dolor vut. Placerat pellentesque ut enim lorem urna egestas, integer adipiscing etiam eu, et eros pulvinar lundium tincidunt eu pid, pellentesque adipiscing augue tincidunt rhoncus lacus? Dictumst egestas, eros. Nascetur mid mus adipiscing tincidunt magna rhoncus a duis odio! Ridiculus odio facilisis, tempor, nunc, vel sit. Nisi augue pulvinar pulvinar eu nisi sagittis scelerisque! In amet! Phasellus pulvinar proin mauris dis vut cras integer ultrices! In ultrices, sed scelerisque pellentesque aliquet placerat turpis dignissim.','image' => 'na.png','user_id' => '1','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),'deleted_at' => null]);
        DB::table('techniques')->insert(['title' => 'Sublimacion','about' => 'Turpis turpis odio enim. Urna eu rhoncus nisi? Aliquet placerat magnis porta nisi? Eros porttitor a! Dignissim sit, non placerat, et! Magna, sit habitasse, mattis integer in, egestas purus augue quis tincidunt? Est, vut, natoque! Porta velit augue dis auctor aliquet augue augue scelerisque! Sed, penatibus rhoncus nascetur? Vel placerat pulvinar tincidunt urna ut, phasellus lorem non mus porta et nunc, ultrices eu nascetur, sagittis, mattis dictumst cras dignissim, integer. Aliquam magnis. Nunc amet ultrices rhoncus et tortor mus auctor, integer tortor pellentesque, ultrices placerat ac quis arcu elit, proin.','detail' => 'Massa, phasellus massa, ac pellentesque, auctor rhoncus aliquet dis, tempor dis sociis auctor! Ultricies urna dolor vut. Placerat pellentesque ut enim lorem urna egestas, integer adipiscing etiam eu, et eros pulvinar lundium tincidunt eu pid, pellentesque adipiscing augue tincidunt rhoncus lacus? Dictumst egestas, eros. Nascetur mid mus adipiscing tincidunt magna rhoncus a duis odio! Ridiculus odio facilisis, tempor, nunc, vel sit. Nisi augue pulvinar pulvinar eu nisi sagittis scelerisque! In amet! Phasellus pulvinar proin mauris dis vut cras integer ultrices! In ultrices, sed scelerisque pellentesque aliquet placerat turpis dignissim.','image' => 'na.png','user_id' => '1','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),'deleted_at' => null]);
        DB::table('techniques')->insert(['title' => 'Sublimacion','about' => 'Turpis turpis odio enim. Urna eu rhoncus nisi? Aliquet placerat magnis porta nisi? Eros porttitor a! Dignissim sit, non placerat, et! Magna, sit habitasse, mattis integer in, egestas purus augue quis tincidunt? Est, vut, natoque! Porta velit augue dis auctor aliquet augue augue scelerisque! Sed, penatibus rhoncus nascetur? Vel placerat pulvinar tincidunt urna ut, phasellus lorem non mus porta et nunc, ultrices eu nascetur, sagittis, mattis dictumst cras dignissim, integer. Aliquam magnis. Nunc amet ultrices rhoncus et tortor mus auctor, integer tortor pellentesque, ultrices placerat ac quis arcu elit, proin.','detail' => 'Massa, phasellus massa, ac pellentesque, auctor rhoncus aliquet dis, tempor dis sociis auctor! Ultricies urna dolor vut. Placerat pellentesque ut enim lorem urna egestas, integer adipiscing etiam eu, et eros pulvinar lundium tincidunt eu pid, pellentesque adipiscing augue tincidunt rhoncus lacus? Dictumst egestas, eros. Nascetur mid mus adipiscing tincidunt magna rhoncus a duis odio! Ridiculus odio facilisis, tempor, nunc, vel sit. Nisi augue pulvinar pulvinar eu nisi sagittis scelerisque! In amet! Phasellus pulvinar proin mauris dis vut cras integer ultrices! In ultrices, sed scelerisque pellentesque aliquet placerat turpis dignissim.','image' => 'na.png','user_id' => '1','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),'deleted_at' => null]);
        DB::table('techniques')->insert(['title' => 'Sublimacion','about' => 'Turpis turpis odio enim. Urna eu rhoncus nisi? Aliquet placerat magnis porta nisi? Eros porttitor a! Dignissim sit, non placerat, et! Magna, sit habitasse, mattis integer in, egestas purus augue quis tincidunt? Est, vut, natoque! Porta velit augue dis auctor aliquet augue augue scelerisque! Sed, penatibus rhoncus nascetur? Vel placerat pulvinar tincidunt urna ut, phasellus lorem non mus porta et nunc, ultrices eu nascetur, sagittis, mattis dictumst cras dignissim, integer. Aliquam magnis. Nunc amet ultrices rhoncus et tortor mus auctor, integer tortor pellentesque, ultrices placerat ac quis arcu elit, proin.','detail' => 'Massa, phasellus massa, ac pellentesque, auctor rhoncus aliquet dis, tempor dis sociis auctor! Ultricies urna dolor vut. Placerat pellentesque ut enim lorem urna egestas, integer adipiscing etiam eu, et eros pulvinar lundium tincidunt eu pid, pellentesque adipiscing augue tincidunt rhoncus lacus? Dictumst egestas, eros. Nascetur mid mus adipiscing tincidunt magna rhoncus a duis odio! Ridiculus odio facilisis, tempor, nunc, vel sit. Nisi augue pulvinar pulvinar eu nisi sagittis scelerisque! In amet! Phasellus pulvinar proin mauris dis vut cras integer ultrices! In ultrices, sed scelerisque pellentesque aliquet placerat turpis dignissim.','image' => 'na.png','user_id' => '1','created_at' => \Carbon\Carbon::now()->toDateTimeString(),'updated_at' => \Carbon\Carbon::now()->toDateTimeString(),'deleted_at' => null]);
    }
}
