language: php

php:
  - 5.5.9
  - hhvm

env:
  - DB=mysql

before_script:
  - composer install
  - mv .env.example .env
  - php artisan key:generate
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS abproject15;" -uroot; fi

script:
  - phpunit